name: flutter_tencent_im_ui
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  tencent_im_sdk_plugin: ^3.2.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  json_annotation: ^4.0.1
  provider: ^5.0.0
  url_launcher: ^6.0.5
  shared_preferences: ^2.0.5
  image_picker: ^0.8.0
  flutter_plugin_record: ^1.0.1
  file_picker: ^3.0.2+2
  video_player: ^2.1.1
  transparent_image: ^2.0.0
  video_thumbnail: ^0.3.3
  device_info: ^2.0.2
  flutter_slidable: ^0.6.0
  crypto: ^3.0.1
  path_provider: ^2.0.1
  loading_indicator: ^2.0.1
  fluttertoast: ^8.0.6
  webview_flutter: ^2.0.10
  flutter_sound: ^8.2.5
  record: ^3.0.0
  audioplayers: ^0.19.1
  open_file: ^3.2.1
  flutter_filereader: 3.0.0
  flutter_dynamic_widgets:
    git:
      url: https://github.com/hui-z/flutter_dynamic_widgets.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  # To add assets to your package, add an assets section, like this:

  assets:
    - images/logo.png
    - images/person.png
    - images/file.png
    - images/voice_volume_1.png
    - images/voice_volume_2.png
    - images/voice_volume_3.png
    - images/voice_volume_4.png
    - images/voice_volume_5.png
    - images/voice_volume_6.png
    - images/voice_volume_7.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
